fix: cleanup [skip-native]

diff --git a/.github/workflows/previews-cleanup.yml b/.github/workflows/previews-cleanup.yml
--- a/.github/workflows/previews-cleanup.yml
+++ b/.github/workflows/previews-cleanup.yml
@@ -39,30 +39,36 @@ jobs:
         id: android_env
         working-directory: ./apps/native-ui-storybook
         run: |
-          GITHUB_PAT_TOKEN=${{ secrets.DS_ACTION_READ_PAT }} ARTIFACT_NAME=${{ github.event.before }}-env-android node ./scripts/getArtifacts.js
+          GITHUB_PAT_TOKEN=${{ secrets.DS_ACTION_READ_PAT }} ARTIFACT_NAME=${{ github.event.before }}-env-android node ./scripts/getArtifacts.js || echo "No Android .env file found"
 
-      - name: 🏗 Load Android .env file
-        uses: xom9ikk/dotenv@v2
-        with:
-          path: ./apps/native-ui-storybook
-          mode: 'android'
-
-      - name: 🧽 Cleanup Android preview
+      - name: 🏗 Load Android .env file and Cleanup Preview
         run: |
-          curl -X DELETE https://${{ secrets.APPETIZE_API_TOKEN }}@api.appetize.io/v1/apps/${{env.ANDROID_API_KEY}}
+          if [ -f "./apps/native-ui-storybook/.env.android" ]; then
+            # Load .env file
+            echo "Loading Android .env file..."
+            # Assuming you have a script or command to load the .env file
+            source ./apps/native-ui-storybook/.env.android
+            # Cleanup Android preview
+            curl -X DELETE https://${{ secrets.APPETIZE_API_TOKEN }}@api.appetize.io/v1/apps/${ANDROID_API_KEY}
+          else
+            echo "No Android .env file found, skipping cleanup."
+          fi
 
       - name: 🏗 Restore .env for iOS
         id: ios_env
         working-directory: ./apps/native-ui-storybook
         run: |
-          GITHUB_PAT_TOKEN=${{ secrets.DS_ACTION_READ_PAT }} ARTIFACT_NAME=${{ github.event.before }}-env-ios node ./scripts/getArtifacts.js
+          GITHUB_PAT_TOKEN=${{ secrets.DS_ACTION_READ_PAT }} ARTIFACT_NAME=${{ github.event.before }}-env-ios node ./scripts/getArtifacts.js || echo "No iOS .env file found"
 
-      - name: 🏗 Load iOS .env file
-        uses: xom9ikk/dotenv@v2
-        with:
-          path: ./apps/native-ui-storybook
-          mode: 'ios'
-
-      - name: 🧽 Cleanup iOS preview
+      - name: 🏗 Load iOS .env file and Cleanup Preview
         run: |
-          curl -X DELETE https://${{ secrets.APPETIZE_API_TOKEN }}@api.appetize.io/v1/apps/${{env.IOS_API_KEY}}
+          if [ -f "./apps/native-ui-storybook/.env.ios" ]; then
+            # Load .env file
+            echo "Loading iOS .env file..."
+            # Assuming you have a script or command to load the .env file
+            source ./apps/native-ui-storybook/.env.ios
+            # Cleanup iOS preview
+            curl -X DELETE https://${{ secrets.APPETIZE_API_TOKEN }}@api.appetize.io/v1/apps/${IOS_API_KEY}
+          else
+            echo "No iOS .env file found, skipping cleanup."
+          fi
